export const ROUTES = {
  ACCOUNT_EDIT: '/account/edit',
  APPOINTMENT_DETAIL: `/appointment-detail/[id]`,
  MY_APPOINTMENTS: "/appointments",
  CALL_USER: `/call?user_id={id}`,
  MOCK_FEEDBACK_PAGE: "/appointment-detail/mockFeedbackModal",
  CONVERSATION_FEEDBACK_PAGE: "/appointment-detail/conversationFeedbackForm",
  LOGIN: "/auth/login",
  // HOME: "/",
  FORGET_PASSWORD: "/auth/forget-password",
  RESET_PASSWORD: "/auth/reset-password",
  ONBOARDING: '/onboarding',
  HOME: "/(tabs)/home",
  CALL: '/call',
  //   MY_APPOINTMENTS: "/(tabs)/my-appointments",
};
