import { ServiceType } from "@prisma/client";

export const packageSeed = [
  // IELTS General Training Packages
  {
    name: 'IELTS GT Basic',
    price_bdt: 3000,
    price_usd: 30,
    price_bdt_original: 3500,
    price_usd_original: 35,
    class_count: 8,
    class_duration: 60,
    service_type: ServiceType.ielts_gt,
    description: '8 classes focusing on GT fundamentals',
    is_active: true,
  },
  {
    name: 'IELTS GT Standard',
    price_bdt: 5000,
    price_usd: 50,
    price_bdt_original: 6000,
    price_usd_original: 60,
    class_count: 16,
    class_duration: 60,
    service_type: ServiceType.ielts_gt,
    description: 'Comprehensive GT preparation course',
    is_active: true,
  },
  {
    name: 'IELTS GT Intensive',
    price_bdt: 8000,
    price_usd: 80,
    price_bdt_original: 9000,
    price_usd_original: 90,
    class_count: 24,
    class_duration: 90,
    service_type: ServiceType.ielts_gt,
    description: 'Intensive training with mock tests',
    is_active: true,
  },

  // IELTS Academic Packages
  {
    name: 'IELTS Academic Starter',
    price_bdt: 3500,
    price_usd: 35,
    price_bdt_original: 4000,
    price_usd_original: 40,
    class_count: 8,
    class_duration: 60,
    service_type: ServiceType.ielts_academic,
    description: 'Introduction to Academic IELTS',
    is_active: true,
  },
  {
    name: 'IELTS Academic Pro',
    price_bdt: 6000,
    price_usd: 60,
    price_bdt_original: 7000,
    price_usd_original: 70,
    class_count: 16,
    class_duration: 60,
    service_type: ServiceType.ielts_academic,
    description: 'Complete Academic IELTS preparation',
    is_active: true,
  },
  {
    name: 'IELTS Academic Master',
    price_bdt: 9000,
    price_usd: 90,
    price_bdt_original: 10000,
    price_usd_original: 100,
    class_count: 24,
    class_duration: 90,
    service_type: ServiceType.ielts_academic,
    description: 'Advanced training with writing evaluation',
    is_active: true,
  },

  // Spoken English Packages
  {
    name: 'Spoken Beginner',
    price_bdt: 2000,
    price_usd: 20,
    price_bdt_original: 2500,
    price_usd_original: 25,
    class_count: 8,
    class_duration: 45,
    service_type: ServiceType.spoken,
    description: 'Basic conversation skills',
    is_active: true,
  },
  {
    name: 'Spoken Intermediate',
    price_bdt: 3500,
    price_usd: 35,
    price_bdt_original: 4000,
    price_usd_original: 40,
    class_count: 12,
    class_duration: 45,
    service_type: ServiceType.spoken,
    description: 'Improve fluency and vocabulary',
    is_active: true,
  },
  {
    name: 'Spoken Advanced',
    price_bdt: 5000,
    price_usd: 50,
    price_bdt_original: 6000,
    price_usd_original: 60,
    class_count: 16,
    class_duration: 60,
    service_type: ServiceType.spoken,
    description: 'Master professional communication',
    is_active: true,
  },

  // Speaking Mock Test Packages
  {
    name: 'Single Mock Test',
    price_bdt: 500,
    price_usd: 5,
    price_bdt_original: 600,
    price_usd_original: 6,
    class_count: 1,
    class_duration: 30,
    service_type: ServiceType.speaking_mock_test,
    description: 'One full speaking test with feedback',
    is_active: true,
    sessions_count: 1
  },
  {
    name: 'Test Package (3 Tests)',
    price_bdt: 1200,
    price_usd: 12,
    price_bdt_original: 1500,
    price_usd_original: 15,
    class_count: 3,
    class_duration: 30,
    service_type: ServiceType.speaking_mock_test,
    description: 'Three speaking tests with detailed feedback',
    is_active: true,
    sessions_count: 3
  },
  {
    name: 'Comprehensive Test Package',
    price_bdt: 2000,
    price_usd: 20,
    price_bdt_original: 2500,
    price_usd_original: 25,
    class_count: 5,
    class_duration: 30,
    service_type: ServiceType.speaking_mock_test,
    description: 'Five tests with personalized improvement plan',
    is_active: true,
    sessions_count: 5
  },

  // Conversation Packages
  {
    name: 'Casual Conversation',
    price_bdt: 1500,
    price_usd: 15,
    price_bdt_original: 1800,
    price_usd_original: 18,
    class_count: 4,
    class_duration: 45,
    service_type: ServiceType.conversation,
    description: 'Practice everyday conversations',
    is_active: true,
    sessions_count: 1
  },
  {
    name: 'Business Conversation',
    price_bdt: 2500,
    price_usd: 25,
    price_bdt_original: 3000,
    price_usd_original: 30,
    class_count: 8,
    class_duration: 45,
    service_type: ServiceType.conversation,
    description: 'Professional communication practice',
    is_active: true,
    sessions_count: 3
  },
  {
    name: 'Cultural Exchange',
    price_bdt: 3500,
    price_usd: 35,
    price_bdt_original: 4000,
    price_usd_original: 40,
    class_count: 12,
    class_duration: 60,
    service_type: ServiceType.conversation,
    description: 'In-depth discussions on various topics',
    is_active: true,
    sessions_count: 5
  },
];
