

export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  ACCOUNT_EDIT: "/account/edit",
  ACCOUNT_PASSWORD: "/account/password",
  ORDERS: "/orders",
  ORDER_DETAILS: "/orders/[id]",
  DEVICE_DIAGNOSIS: "/device-diagnosis",
  BOOKING_DETAILS: "/appointment/[id]",
  PACKAGES: "/packages",
  MOCKTEST_REPORT: "/appointment/mocktestReport",
  CONVERSATION_REPORT: "/appointment/conversationReport",
  BOOKINGS: "/bookings",
  BOOKING_PAYMENT: "/appointment/payment",
  BOOKING_DATETIME: "/appointment/datetime",
  CART: "/books/cart",
  BOOK_DETAILS: "/books/[id]",
  BOOKS: "/books",
  EXAM_REGISTRATION_FORM: "/exam/registration-form",
  ONLINE_REGISTRATION_FORM: "/online-course/registration-form",
  FORGET_PASSWORD: "/forget-password",
  VERIFY_OTP: "/verify-otp",
  RESET_PASSWORD: "/reset-password",
  CHECKOUT: "/books/checkout",
  LANDING: "/landing",
  TABS: "/(tabs)",
  REGISTRATION: "/registration",
  EXAM_REGISTRATION: "/exam/exam-registration",
  ONLINE_COURSE_DETAILS: "/online-course/details",
  ONLINE_COURSE: "/online-course",
  STUDY_ABROAD: "/study-abroad",
  CALL: "/call",
  MY_APPOINTMENT: '(tabs)/mybookings',
  EXAM_PACKAGES: '/exam/packages',
  ONLINE_COURSE_PACKAGES: '/online-course/packages',
  STUDY_ABROAD_REGISTRATION: '/study-abroad/registration-form',
};
